packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'storybook'
  # all packages in subdirs of components/
  #  - 'components/**'
  # exclude packages that are inside test directories
  - '!**/__tests__/**'
  - '!**/lib/**'
  - '!**/dist/**'
